export const TOGGLE_GRID_BUTTON = 'TOGGLE_GRID_BUTTON';

export const UPDATE_STATUS = 'UPDATE_STATUS';

export const TOGGLE_IS_PLAYING = 'TOGGLE_IS_PLAYING';

export const SET_STATE_FROM_SOCKET = 'SET_STATE_FROM_SOCKET';

export const ADD_USER = 'ADD_USER';

export const REMOVE_USER = 'REMOVE_USER';
